[package]
license = ["Apache-2.0"]
keywords = ["AI/Chat", "Cost/Paid", "ChatGPT", "GPT-3.5", "Vendor/OpenAI"]
org = "ballerinax"
name = "openai.chat"
icon = "icon.png"
distribution = "2201.3.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.9.0"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
