[package]
license = ["Apache-2.0"]
keywords = ["AI/OpenAI", "Cost/Paid", "fine-tune", "GPT-3 fine-tune"]
org = "ballerinax"
name = "openai.finetunes"
icon = "icon.png"
distribution = "2201.4.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
