[package]
license = ["Apache-2.0"]
keywords = ["AI/Fine-tunes", "OpenAI", "Cost/Paid", "Fine-tunes", "Files", "Models", "Vendor/OpenAI"]
org = "ballerinax"
name = "openai.finetunes"
icon = "icon.png"
distribution = "2201.3.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.9.0"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
