[package]
license = ["Apache-2.0"]
keywords = ["AI/OpenAI", "Cost/Paid", " Text moderations", "OpenAI moderations"]
org = "ballerinax"
name = "openai.moderations"
icon = "icon.png"
distribution = "2201.4.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
